pivotal:
  app:
    symbols:
      it: DVMT,IBM,AAPL,GOOG
      fs: JPM,C,MS,BAC,GS
---
spring:
  profiles: local
  jpa:
     hibernate:
        ddl-auto: update
server:
  port: 8080
---
spring:
  profiles: cloud
  jpa:
     hibernate:
        ddl-auto: update
